class Zona
{
  String colonia;

 String get getZona => colonia;
 
 set setZona(String colonia) 
  {
      urbana(colonia)?this.colonia     =  "Urbana":
      conurbada(colonia)?this.colonia  =  "Conurbada":
                          this.colonia =  "Nuevos desarrollos";
      
  }  
 Zona({this.colonia});
 

   bool urbana(String colonia) {
    List<String> lurbana = [
      "Acapulco de Juárez Centro",
      "Del Hueso",
      "Del Panteón",
      "El Capire",
      "Pozo de la Nación",
      "Hornos Insurgentes",
      "Progreso",
      "13 de Junio",
      "Hornos",
      "Real de Acapulco",
      "Cuerería",
      "Hospital",
      "La Lima",
      "Las Crucitas",
      "Petaquillas",
      "El Mesón",
      "Del Teconche",
      "La Candelaria",
      "La Guinea",
      "La Pinzona",
      "La Pocita",
      "Los Tepetates",
      "Cumbres INFONAVIT",
      "Farallón INFONAVIT",
      "Flamingos INFONAVIT",
      "Playa Roqueta",
      "Tambuco",
      "Club Residencial las Américas",
      "Bodega",
      "Las Playas",
      "Península de las Playas",
      "Vicente Guerrero",
      "Ángel Aguirre",
      "Corregidora",
      "Ignacio Manuel Altamirano",
      "Jardín Azteca",
      "Nueva Jerusalén",
      "Reforma Agraria",
      "Roca de Oro",
      "Pedregoso",
      "Ampliación San Isidro",
      "Valle de las Flores",
      "Brisas del Mar",
      "Tepeyac",
      "Los Mangos",
      "Excampo de Tiro",
      "Jardín Palmas",
      "Las Joyas",
      "SEMARNAP",
      "Puesta del Sol",
      "Balcones al Mar",
      "Generación 2000",
      "La Nueva Era",
      "Ricardo Morlett Sutter",
      "Universitaria",
      "Venustiano Carranza",
      "Nueva Era",
      "Rubén Jaramillo",
      "Luis Donaldo Colosio",
      "Marbella",
      "Mozimba",
      "Vicente Lombardo Toledano",
      "Antorcha Revolucionaria",
      "Mozimba 1a Secc",
      "José López Portillo INFONAVIT",
      "Mozimba Secc Jardín",
      "Adolfo López Mateos",
      "Potrerillo",
      "Mozimba FOVISSSTE",
      "La Mira",
      "Los Naranjos",
      "Municipal",
      "Taxco",
      "Los Naranjitos",
      "Las Marañonas",
      "Leonardo Rodriguez Alcaine",
      "Vicente Guerrero FOVISSSTE",
      "Independencia",
      "Palma Sola",
      "Ampliación Palma Sola",
      "Constituyentes",
      "Santa Cecilia",
      "Guadalupe Victoria",
      "María de La O",
      "Morelos",
      "Santa Cruz",
      "Olímpica",
      "Silvestre Castro",
      "Juan R Escudero",
      "Ampliación Silvestre Castro",
      "Solidaridad",
      "Alta Cuauhtémoc",
      "Bellavista",
      "Cuauhtémoc",
      "Ampliación Cuauhtémoc",
      "El Mirador",
      "Ampliación Bellavista",
      "Vista Alegre",
      "Jardín Mangos",
      "La Florida INFONAVIT",
      "La Florida",
      "Hogar Moderno",
      "Miguel Alemán",
      "Aguas Blancas",
      "Carabalí Centro",
      "La Fabrica",
      "Palmar de Carabalí",
      "Cuauhtémoc INFONAVIT",
      "Frontera",
      "La Laja",
      "La Laja Parte Alta",
      "Alta Progreso INFONAVIT",
      "Altamira",
      "Ampliación Altamira Norte",
      "Burócrata",
      "Francisco Villa",
      "Margarita de Gortari",
      "6 de Enero",
      "Alta Progreso",
      "Panorámica",
      "Revolución del Sur",
      "Buenavista",
      "Guerrero Es Primero",
      "Periodistas",
      "Unidad Obrera",
      "La Providencia",
      "La Quebradora",
      "Loma Bonita",
      "Vista Hermosa",
      "Alianza Popular",
      "Barranca de la Laja",
      "Bocamar",
      "Las Américas",
      "Las Anclas",
      "Militar",
      "El Roble",
      "Marroquín",
      "Santa Elena",
      "Del Valle",
      "Garita de Juárez",
      "Loma Hermosa",
      "Pacifico",
      "20 de Noviembre",
      "Gustavo Diaz Ordaz",
      "Magallanes",
      "Rodrigo de Triana",
      "Las Cumbres",
      "Lomas de Magallanes",
      "Cumbres Diana",
      "Magisterio Guerrerense",
      "Bosques de la Cañada",
      "Cumbres de Figueroa",
      "Pablo Galeana",
      "Cañada de los Amates",
      "Club Deportivo",
      "Condesa",
      "Farallón",
      "INFONAVIT Centro Acapulco",
      "Jardín de los Amates",
      "Villas Condesa",
      "El Palmar",
      "Graciano Sanchez",
      "Del PRI",
      "Electricistas",
      "Villa los Mangos",
      "16 de Noviembre",
      "El Porvenir",
      "SEDESOL Dos",
      "Placido Domingo Sección A",
      "Tamarindos",
      "Nueva Generación",
      "Fidel Velázquez Sect 1",
      "Bascula",
      "Industrial",
      "Costa azul",
      "San Miguel",
      "Emilio M Gonzalez",
      "Ángel Aguirre Rivero",
      "Ampliación el Paraíso",
      "Ruffo Figueroa",
      "Melchor Ocampo",
      "Cumbres Llano Largo",
      "Lomas de Costa Azul",
      "Balcones de Costa Azul",
      "Hermenegildo Galeana",
      "Reforma de Costa Azul",
      "Praderas de Costa Azul",
      "Costa Azul",
      "23 de Noviembre",
      "Centro de Convenciones",
      "Icacos",
      "Alta Icacos",
      "PEMEX",
      "Brisamar",
      "Joyas de Brisamar",
      "Icacos Prolongación",
      "Club Residencial las Brisas",
      "Brisas Diamante",
      "Hotel las Brisas",
      "Base Naval Icacos",
      "Pichilingue",
      "Brisas del Marqués",
      "El Glomar",
      "Las Brisas 1",
      "Las Brisas 2",
      "Marina Brisas",
      "La Chaparrita",
      "Olinalá Princess",
      "Parque Ecológico de Viveristas",
      "Plan de los Amates",
      "Rubén Robles Catalán",
      "Villas Paraíso Secc I",
      "Pie de La Cuesta",
      "Cervantes Delgado",
      "Las Primaveras",
      "Los Mangos (El Quemado)",
    ];
    for (var item in lurbana) {
      if (item == colonia) {
        return true;
      }
    }
    return false;
  }

  bool conurbada(String colonia) {
    List<String> lconurbada = [
      "La Poza",
      "20 de Abril",
      "El Paraíso",
      "Miramar",
      "Costa Brava Terranova",
      "Emiliano Zapata",
      "Ampliación Emiliano Zapata",
      "Leona Vicario",
      "Ricardo Flores Magón",
      "Tierra y Libertad",
      "24 de Octubre",
      "Caudillo del Sur",
      "Fidel Velázquez Sanchez",
      "México",
      "Ampliación Lomas Verdes",
      "C N C",
      "Yoloxochil",
      "Sinai",
      "Ampliación Sinai",
      "Genaro Vázquez",
      "Roberto Esperon",
      "Victoria Rosales",
      "Alejo Peralta",
      "Rubén Figueroa",
      "La Frontera",
      "Democrática",
      "Ampliación Arroyo Seco",
      "Batalla Cardenista",
      "Agrícola",
      "La Esmeralda",
      "La Mica",
      "Emperador Moctezuma",
      "Nopalitos",
      "Villa Sol",
      "La Venta",
      "SEDESOL Uno",
      "El Tanque",
      "Valle del Palmar II",
      "Paraíso Palmar III",
      "Betania",
      "Valle del Palmar I",
      "Ampliación la Mica",
      "Paso Limonero",
      "Villas Real Hacienda",
      "Barrio Nuevo",
      "Ecologista",
      "Fuentes del Maurel II",
      "Renacimiento",
      "Arroyo Seco",
      "Nuevo Capire",
      "Primero de Mayo",
      "Coheteros",
      "Nueva Luz",
      "Villa Guerrero",
      "La Cima",
      "Benito Juárez",
      "Lázaro Cárdenas",
      "Parotas",
      "Ampliación Miguel Hidalgo",
      "Ampliación Niños Héroes",
      "Amin Zarur Menez",
      "Ampliación las Parotas",
      "Ampliación Miguel de La Madrid",
      "Niños Héroes",
      "Obrera",
      "Ampliación Lázaro Cárdenas",
      "CNOP",
      "2 de Febrero",
      "Las Torres",
      "Jacarandas",
      "Leyes de Reforma",
      "Narciso Mendoza",
      "Postal",
      "Tecnológica",
      "Arboledas",
      "Unidos Por Guerrero",
      "José María Izazaga",
      "San Agustin",
      "Villa de las Flores",
      "José López Portillo",
      "Club Campestre",
      "Coral",
      "Fuentes del Maurel I",
      "Huertas de Santa Elena",
      "Las Cruces",
      "Los Limoncitos",
      "Luz y Fuerza",
      "Libertadores",
      "Corales",
      "Loma Larga",
      "Villa Tulipanes",
      "Cereso I",
      "Ampliación José López Portillo",
      "Ampliación Simón Bolívar",
      "Simón Bolívar",
      "Villa Madero",
      "Francisco Ruiz Massieu",
      "José María Pino Suárez",
      "Movimiento Territorial",
      "Nicolás Bravo",
      "Paraíso",
      "15 de Septiembre",
      "Revolución de Octubre",
      "Nicolás Bravo Junto A López Portillo",
      "Miguel Terrazas",
      "La Libertad",
      "Ampliación la Libertad",
      "Los Lirios",
      "Ampliación los Lirios",
      "Amadeo Vidales",
      "Canuto Nogueda",
      "5 de Mayo",
      "Del rastro",
      "Los Manantiales",
      "Héroes de Guerrero",
      "La Sabana",
      "Los Dragos",
      "Mártir de Cuilapan",
      "La Maquina",
      "Ampliación la Maquina",
      "Rastro Viejo",
      "Salinas de Gortari",
      "El Coloso INFONAVIT",
      "Potrero de La Mora",
      "Apolonio Castillo",
      "Piedra Azul",
      "Piedra Roja",
      "Alta Loma la Esperanza",
      "La Esperanza",
      "La Navidad",
      "La Parota",
      "Milenia",
      "Nuevo Cayaco",
      "Navidad de Llano Largo",
      "Praderas de Guadalupe",
      "Nuevo Centro de Población",
      "Lomas del Marqués",
      "Alborada Cardenista",
      "Ciudad Luis Donaldo Colosio",
      "Granjas del Marqués",
      "Jardín Princesas I",
      "Jardín Princesas II",
      "Puerto Marqués",
      "La Princesa",
      "Princess del Marqués Secc I",
      "Rinconada del Mar",
      "Villas del Paraíso Secc II",
      "Villas Diamante I",
      "Villas Diamante II",
      "Los Arcos",
      "Alfredo V Bonfil",
      "3 Vidas",
      "Cuquita Massieu",
      "El Podrido",
      "2 Soles",
      "Nuevo Puerto Marqués",
      "Club Playa Mar",
      "Villas de Golf Diamante",
      "Villas Princess I",
      "Villas Princess II",
      "Copacabana",
      "Princess del Marqués II",
      "Playa Diamante",
      "Real Diamante",
      "3 de Abril",
      "Villas Xcaret",
      "Altos de Miramar",
      "Altos del Marqués",
      "La Lajita",
      "Vista Brisa",
      "19 de Noviembre",
      "La Guadalupana",
      "Barrio Nuevo de los Muertos",
      "Acapulco (Gral. Juan N. Álvarez)",
      "El Quemado",
      "El Veladero (Veladero Morelos)",
      "Los Órganos San Agustín",
      "Carabalí",
      "El Salto",
      "Las Plazuelas",
      "El Metlapil",
      "Tuncingo",
      "Cayaco",
      "Joyas del Marques",
      "La Marquesa",
      "Misión del Mar",
      "La Zanja O La Poza",
      "Llano Largo",
      "Costa Dorada",
      "Tres Palos",
      "El Zapote",
      "Lomas del Aire",
      "Los Órganos de Juan R. Escudero",
      "Las Tortolitas",
      "Xaltianguis",
      "Xolapa",
      "Lagunillas",
      "Las Flores",
      "Las Pilitas",
      "Retén",
      "Kilómetro 21",
      "Kilómetro 22",
      "Pueblo Madero",
      "Kilómetro 48",
      "Las Marías",
      "Kilómetro 45",
      "Piedra Imán",
      "Kilómetro 30",
      "La Calera",
      "El Pelillo",
      "San Antonio",
      "Tasajeras",
      "Texca",
      "Altos del Camarón",
      "Dos Arroyos",
      "Las Sabanillas",
      "Ejido Nuevo",
      "Kilómetro 40",
      "Kilómetro 42",
      "La Sierrita",
      "Lomas de San Juan",
      "Agua Zarca de la Peña",
      "Amatepec",
      "Huajintepec",
      "Pochotlaxco",
      "La Garrapata",
      "Las Parotas",
      "San José Cacahuatepec",
      "Lomas de Chapultepec",
      "Cacahuate",
      "El Bejuco",
      "El Campanario",
      "Huamuchitos",
      "La Concepción",
      "10 de Abril",
      "Cerro de Piedra",
      "El Arenal",
      "Salsipuedes",
      "San Andrés Playa Encantada",
      "Apanhuac",
      "Cacahuatepec",
      "El Cantón",
      "Parotillas",
    ];

    for (var item in lconurbada) {
      if (item == colonia) {
        return true;
      }
    }
    return false;
  }

}